// Mock data for the admin dashboard

export const mockOrders = [
  {
    id: "ORD1001",
    customerName: "Rahul Sharma",
    customerEmail: "rahul.sharma@example.com",
    products: [
      { id: "PRD001", name: "Unflavored NutriPro+", price: 1499, quantity: 2 },
      { id: "PRD002", name: "Chocolate NutriPro+", price: 1699, quantity: 1 },
    ],
    total: 4697,
    status: "delivered",
    date: "2023-11-15",
    shippingAddress: {
      address: "123 Main Street",
      city: "Mumbai",
      state: "Maharashtra",
      postalCode: "400001",
      country: "India",
    },
  },
  {
    id: "ORD1002",
    customerName: "Priya Patel",
    customerEmail: "priya.patel@example.com",
    products: [{ id: "PRD003", name: "Strawberry NutriPro+", price: 1699, quantity: 1 }],
    total: 1699,
    status: "shipped",
    date: "2023-11-20",
    shippingAddress: {
      address: "456 Park Avenue",
      city: "Delhi",
      state: "Delhi",
      postalCode: "110001",
      country: "India",
    },
  },
  {
    id: "ORD1003",
    customerName: "Amit Singh",
    customerEmail: "amit.singh@example.com",
    products: [
      { id: "PRD001", name: "Unflavored NutriPro+", price: 1499, quantity: 1 },
      { id: "PRD002", name: "Chocolate NutriPro+", price: 1699, quantity: 1 },
      { id: "PRD003", name: "Strawberry NutriPro+", price: 1699, quantity: 1 },
    ],
    total: 4897,
    status: "pending",
    date: "2023-11-25",
    shippingAddress: {
      address: "789 Lake Road",
      city: "Bangalore",
      state: "Karnataka",
      postalCode: "560001",
      country: "India",
    },
  },
  {
    id: "ORD1004",
    customerName: "Neha Gupta",
    customerEmail: "neha.gupta@example.com",
    products: [{ id: "PRD002", name: "Chocolate NutriPro+", price: 1699, quantity: 3 }],
    total: 5097,
    status: "delivered",
    date: "2023-11-10",
    shippingAddress: {
      address: "101 Hill View",
      city: "Chennai",
      state: "Tamil Nadu",
      postalCode: "600001",
      country: "India",
    },
  },
  {
    id: "ORD1005",
    customerName: "Vikram Mehta",
    customerEmail: "vikram.mehta@example.com",
    products: [{ id: "PRD001", name: "Unflavored NutriPro+", price: 1499, quantity: 1 }],
    total: 1499,
    status: "cancelled",
    date: "2023-11-05",
    shippingAddress: {
      address: "202 River Side",
      city: "Kolkata",
      state: "West Bengal",
      postalCode: "700001",
      country: "India",
    },
  },
  {
    id: "ORD1006",
    customerName: "Ananya Reddy",
    customerEmail: "ananya.reddy@example.com",
    products: [{ id: "PRD003", name: "Strawberry NutriPro+", price: 1699, quantity: 2 }],
    total: 3398,
    status: "shipped",
    date: "2023-11-22",
    shippingAddress: {
      address: "303 Mountain View",
      city: "Hyderabad",
      state: "Telangana",
      postalCode: "500001",
      country: "India",
    },
  },
  {
    id: "ORD1007",
    customerName: "Rajesh Kumar",
    customerEmail: "rajesh.kumar@example.com",
    products: [
      { id: "PRD001", name: "Unflavored NutriPro+", price: 1499, quantity: 1 },
      { id: "PRD003", name: "Strawberry NutriPro+", price: 1699, quantity: 1 },
    ],
    total: 3198,
    status: "pending",
    date: "2023-11-28",
    shippingAddress: {
      address: "404 Ocean Front",
      city: "Pune",
      state: "Maharashtra",
      postalCode: "411001",
      country: "India",
    },
  },
  {
    id: "ORD1008",
    customerName: "Sanjay Verma",
    customerEmail: "sanjay.verma@example.com",
    products: [{ id: "PRD002", name: "Chocolate NutriPro+", price: 1699, quantity: 2 }],
    total: 3398,
    status: "delivered",
    date: "2023-11-12",
    shippingAddress: {
      address: "505 Valley Road",
      city: "Ahmedabad",
      state: "Gujarat",
      postalCode: "380001",
      country: "India",
    },
  },
]

export const mockProducts = [
  {
    id: "PRD001",
    name: "Unflavored NutriPro+",
    description: "Pure and natural blend with the original taste of dry fruits",
    price: 1499,
    stock: 50,
    image: "/images/unflavored.jpeg",
    flavor: "Unflavored",
    category: "NutriPro+",
  },
  {
    id: "PRD002",
    name: "Chocolate NutriPro+",
    description: "Rich chocolate flavor combined with nutritious dry fruits",
    price: 1699,
    stock: 45,
    image: "/images/chocolate.jpeg",
    flavor: "Chocolate",
    category: "NutriPro+",
  },
  {
    id: "PRD003",
    name: "Strawberry NutriPro+",
    description: "Sweet strawberry taste with all the goodness of dry fruits",
    price: 1699,
    stock: 40,
    image: "/images/strawberry.jpeg",
    flavor: "Strawberry",
    category: "NutriPro+",
  },
]
